line_width: 60  # Maximum line width
tab_size: 4     # Size of tabs
use_tabchars: False  # Use spaces instead of tabs
indent_width: 4  # Number of spaces per indentation level
keyword_case: upper  # Set all keywords to uppercase
command_case: lower  # Set all commands to lowercase
dangle_parens: True  # Avoid dangling parentheses
space_between_parens: True  # Space between parentheses
enable_sort: False  # Disable automatic sorting of arguments
always_wrap: ['include_directories', 'link_directories']
